version: '3'

services:
  postgresql-primary:
    image: postgres:15.1
    ports:
      - '15001:5432'
    volumes:
      - 'manual_postgresql_primary_data:/var/lib/postgresql/data'
      - 'slave_data_volume:/tmp/postgresslave'
      - './postgres_configuration/primary-postgres.conf:/var/lib/postgresql/data/postgresql.conf'
      - './postgres_configuration/primary-pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf'
    environment:
      - POSTGRES_PASSWORD=my_password
  postgresql-secondary:
    image: postgres:15.1
    ports:
      - '15002:5432'
    depends_on:
      - postgresql-primary
    volumes:
      - 'slave_data_volume:/var/lib/postgresql/data'
    environment:
      - POSTGRES_PASSWORD=my_password
volumes:
  manual_postgresql_primary_data:
  slave_data_volume: